apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket-sync-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "phase5" }}
  labels:
    {{- include "websocket-sync-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "websocket-sync-service.selectorLabels" . | nindent 4 }}
