apiVersion: v2
name: audit-service
description: audit service with Dapr
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - audit
  - dapr
  - microservice

maintainers:
  - name: Phase5 Team
    email: team@phase5.dev
