apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notification-service.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "phase5" }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
