apiVersion: v2
name: websocket-sync-service
description: websocket sync service with Dapr
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - websocket
  - dapr
  - microservice

maintainers:
  - name: Phase5 Team
    email: team@phase5.dev
