apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recurring-task-service.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "phase5" }}
  labels:
    {{- include "recurring-task-service.labels" . | nindent 4 }}
