{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-pvc
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
